/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface MaintainUserDTO { 
    address?: string;
    city?: string;
    createdAt?: string;
    email?: string;
    firstName?: string;
    id?: number;
    isBanned?: boolean;
    isConfirmed?: boolean;
    lastLogin?: string;
    lastName?: string;
    phoneNumber?: string;
    updatedAt?: string;
    username?: string;
}