/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Customer } from './customer';
import { OrderDetails } from './orderDetails';

export interface CustomerOrder { 
    amount?: number;
    customer?: Customer;
    date?: string;
    id?: number;
    orderDetails?: OrderDetails;
    orderStatus?: CustomerOrder.OrderStatusEnum;
}
export namespace CustomerOrder {
    export type OrderStatusEnum = 'DELIVERED' | 'PENDING' | 'SENT';
    export const OrderStatusEnum = {
        DELIVERED: 'DELIVERED' as OrderStatusEnum,
        PENDING: 'PENDING' as OrderStatusEnum,
        SENT: 'SENT' as OrderStatusEnum
    };
}