/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CustomerOrder } from './customerOrder';
import { Product } from './product';

export interface OrderDetails { 
    customerOrder?: CustomerOrder;
    id?: number;
    products?: Array<Product>;
    quantity?: number;
    totalPrice?: number;
}