/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ProductCategory } from './productCategory';

export interface Product { 
    description?: string;
    id?: number;
    image?: string;
    name?: string;
    price?: number;
    productCategory?: ProductCategory;
    stock?: number;
    weight?: number;
}