/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ServiceRating { 
    date?: string;
    fromUser?: number;
    id?: number;
    message?: string;
    stars?: number;
    toService?: number;
}