/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {UserInfo} from './userInfo';

export interface UserProfileImage {
  id?: number;
  name?: string;
  picByte?: string;
  type?: string;
  userInfo?: UserInfo;
}
