/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {User} from './user';
import {UserProfileImage} from './userProfileImage';

export interface UserInfo {
  address?: string;
  city?: string;
  email?: string;
  firstName?: string;
  id?: number;
  lastName?: string;
  phoneNumber?: string;
  profileImage?: UserProfileImage;
  user?: User;
}
