export * from './adminController.service';
import {AdminControllerService} from './adminController.service';
import {AuthControllerService} from './authController.service';
import {BasicErrorControllerService} from './basicErrorController.service';
import {ImageUploadControllerService} from './imageUploadController.service';
import {OrderControllerService} from './orderController.service';
import {ProductCategoryControllerService} from './productCategoryController.service';
import {ProductControllerService} from './productController.service';
import {TestControllerService} from './testController.service';
import {UserControllerService} from './userController.service';

export * from './authController.service';
export * from './basicErrorController.service';
export * from './imageUploadController.service';
export * from './orderController.service';
export * from './productCategoryController.service';
export * from './productController.service';
export * from './testController.service';
export * from './userController.service';
export const APIS = [AdminControllerService, AuthControllerService, BasicErrorControllerService, ImageUploadControllerService, OrderControllerService, ProductCategoryControllerService, ProductControllerService, TestControllerService, UserControllerService];
