/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import {Inject, Injectable, Optional} from '@angular/core';
import {HttpClient, HttpEvent, HttpHeaders, HttpParams, HttpResponse} from '@angular/common/http';
import {CustomHttpUrlEncodingCodec} from '../encoder';

import {Observable} from 'rxjs';

import {ResponseEntity} from '../model/responseEntity';
import {UserProfileImage} from '../model/userProfileImage';

import {BASE_PATH} from '../variables';
import {Configuration} from '../configuration';


@Injectable()
export class ImageUploadControllerService {

  public defaultHeaders = new HttpHeaders();
  public configuration = new Configuration();
  protected basePath = 'http://localhost:8080';

  constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
    if (basePath) {
      this.basePath = basePath;
    }
    if (configuration) {
      this.configuration = configuration;
      this.basePath = basePath || configuration.basePath || this.basePath;
    }
  }

  /**
   * getImage
   *
   * @param userImageId userImageId
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getImageUsingGET(userImageId: number, observe?: 'body', reportProgress?: boolean): Observable<UserProfileImage>;

  public getImageUsingGET(userImageId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<UserProfileImage>>;

  public getImageUsingGET(userImageId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<UserProfileImage>>;

  public getImageUsingGET(userImageId: number, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

    if (userImageId === null || userImageId === undefined) {
      throw new Error('Required parameter userImageId was null or undefined when calling getImageUsingGET.');
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      '*/*'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<UserProfileImage>('get', `${this.basePath}/image/get/${encodeURIComponent(String(userImageId))}`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * uplaodImage
   *
   * @param userId userId
   * @param body
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public uplaodImageUsingPOST(userId: number, body?: Object, observe?: 'body', reportProgress?: boolean): Observable<ResponseEntity>;

  public uplaodImageUsingPOST(userId: number, body?: Object, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResponseEntity>>;

  public uplaodImageUsingPOST(userId: number, body?: Object, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResponseEntity>>;

  public uplaodImageUsingPOST(userId: number, body?: Object, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

    if (userId === null || userId === undefined) {
      throw new Error('Required parameter userId was null or undefined when calling uplaodImageUsingPOST.');
    }


    let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
    if (userId !== undefined && userId !== null) {
      queryParameters = queryParameters.set('userId', <any>userId);
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      '*/*'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [
      'application/json',
      'application/octet-stream'
    ];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected != undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    return this.httpClient.request<ResponseEntity>('post', `${this.basePath}/image/upload`,
      {
        body: body,
        params: queryParameters,
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * @param consumes string[] mime-types
   * @return true: consumes contains 'multipart/form-data', false: otherwise
   */
  private canConsumeForm(consumes: string[]): boolean {
    const form = 'multipart/form-data';
    for (const consume of consumes) {
      if (form === consume) {
        return true;
      }
    }
    return false;
  }

}
